# ------------------------------------------------------------
# impostor.nekix.lol
# ------------------------------------------------------------

map $scheme $hsts_header {
    https   "max-age=63072000; preload";
}

server {
  set $forward_scheme http;
  set $server         "192.168.1.11";
  set $port           3001;

  listen 80;
  listen [::]:80;
  listen 443 ssl http2;
  listen [::]:443 ssl http2;

  server_name impostor.nekix.lol;

  ssl_certificate /etc/letsencrypt/live/impostor.nekix.lol/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/impostor.nekix.lol/privkey.pem;

  access_log /data/logs/proxy-host-11_access.log proxy;
  error_log /data/logs/proxy-host-11_error.log warn;

  location /.well-known/acme-challenge/ {
    root /tmp/letsencrypt;
  }

  location / {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass http://192.168.1.11:3001;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
